Custom init script

diff --git a/templates/default/cloudfuse.erb b/templates/default/cloudfuse.erb
--- a/templates/default/cloudfuse.erb
+++ b/templates/default/cloudfuse.erb
@@ -1,15 +1,91 @@
+#! /bin/sh
 #
-# ~/.cloudfuse
+# /etc/init.d/cloudfuse
+# <%= @prefix %>/cloudfuse
 #
 # Generated by Chef for <%= node[:fqdn] %>
 #
 
-username=<%= @username %>
-api_key=<%= @api_key %>
-authurl=<%= @authurl %>
-<% unless @use_snet.nil? %>
-use_snet=<%= @use_snet %> #[True to use snet for connections]
-<% end %>
-<% unless @cache_timeout.nil? %>
-cache_timeout=<%= @cache_timeout %> #[seconds for directory caching, default 600]
-<% end %>
+### BEGIN INIT INFO
+# Provides:          cloudfuse
+# Description:       CloudFuse is a FUSE application which provides access to
+#                    Rackspace Cloud Files (or any other installation of Swift)
+#                    This provides cloudfuse daemon functionality.
+### END INIT INFO
+
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+DAEMON=<%= @prefix %>/cloudfuse
+NAME=cloudfuse
+DESC=cloudfuse
+
+CF_MOUNTPOINT="<%= @mountpoint %>"
+CF_COMMAND_FLAGS="<%= @command_flags %>"
+
+test -x $DAEMON || exit 0
+
+set -e
+
+cloudfuse_start() {
+    PID=$(pidof $NAME) || true
+    if [ -n "$PID" ]; then
+        echo "$DESC daemon is already running (pid $PID)."
+        exit 0
+    else
+    	echo "Starting $DESC daemon"
+        if start-stop-daemon --start --quiet --background \
+            --exec $DAEMON \
+            -- $CF_COMMAND_FLAGS $CF_MOUNTPOINT
+        then
+            sleep 1
+            PID=$(pidof $NAME) || true
+            if [ -z "$PID" ]; then 
+                echo "$DESC daemon failed to start"
+                return 1
+            fi  
+        else
+            return 1
+        fi  
+    fi  
+}
+
+cloudfuse_stop() {
+	echo "Stopping $DESC daemon"
+    umount "$CF_MOUNTPOINT"
+}
+
+case "$1" in
+  start)
+    cloudfuse_start
+    ;;
+  stop)
+    cloudfuse_stop
+    ;;
+  restart)
+    set +e
+    echo "Restarting $DESC daemon"
+    PID=$(pidof $NAME) || true
+    if [ -n "$PID" ]; then
+        cloudfuse_stop
+        sleep 1
+    else
+        echo "$DESC daemon not running, attempting to start it"
+    fi
+    cloudfuse_start
+    ;;
+  status)
+    PID=$(pidof $NAME) || true
+    if [ -n "$PID" ]; then
+        echo "$DESC daemon is running (pid $PID)."
+        exit 0
+    else
+        echo "$DESC daemon is NOT running."
+        exit 1
+    fi
+    exit $? # notreached due to set -e
+    ;;
+  *)
+    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
+    exit 1
+esac
+
+exit 0
